PATH_TO_RAW_DATA = "data/raw/the_Italian_Music_dataset_v1.json"
PATH_TO_PROCESSED_DATA = "data/processed/the_Italian_Music_dataset_v1.csv"
PATH_TO_REGIONS_DATA = "data/processed/regions.csv"
PATH_TO_GENRE_DATA = "data/processed/genre.csv"
PATH_TO_MUSIC_MODEL = "models/music/italian_music_model_v1.pkl"
PATH_TO_MUSIC_MODEL_FEATURES = "models/music/italian_music_columns_v1.pkl"
PATH_TO_LOGGING_FILE = "errors.log"
